import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton  } from '@clerk/nextjs';
import SidebarWrapper from "./Components/Sidebar/SidebarWrapper";
import { auth } from "@clerk/nextjs/server";
import NextTopLoader from "nextjs-toploader";

const nunito = Nunito({ 
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Project Management Systems",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        </head>
        <body className={nunito.className}>
          <NextTopLoader 
            height={2}
            color="#27AE60"
            easing="cubic-bezier(.53,0.21,0,1)"
            
          />
          <ContextProvider>
            <GlobalStyleProvider>
            {userId && <Sidebar />}
              <div className="w-full">{children}</div>
            </GlobalStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
